# Generated by Django 3.2.6 on 2022-03-05 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_mt_config', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted'), ('PIPELINE', 'Pipeline'), ('PASSIVE', 'Passive')], max_length=20)),
                ('status_reason', models.TextField()),
                ('description', models.CharField(max_length=100)),
                ('entity', models.CharField(choices=[('person', 'Person'), ('gesellschaft', 'Gesellschaft')], max_length=20)),
                ('law', models.CharField(choices=[('bgb', 'Bgb'), ('gmbhg', 'Gmbhg'), ('aktg', 'Aktg'), ('hgb', 'Hgb')], max_length=20)),
                ('agent_type', models.CharField(choices=[('private', 'Private'), ('unternehmen', 'Unternehmen'), ('mitarbeiter', 'Mitarbeiter')], max_length=20)),
                ('sub_type', models.CharField(choices=[('freiberuf', 'Freiberuf'), ('gewerbe', 'Gewerbe'), ('mini-geringf', 'Mini-Geringf'), ('sozialv', 'Sozialv'), ('sozialv-frei', 'Sozialv-Frei')], max_length=20)),
                ('level', models.CharField(choices=[('CLIENT', 'Client')], max_length=20)),
                ('tax_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent',
            },
        ),
        migrations.CreateModel(
            name='Asys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmsp', models.DateTimeField(auto_now=True, null=True)),
                ('day', models.PositiveSmallIntegerField(null=True)),
                ('month', models.PositiveSmallIntegerField(null=True)),
                ('year', models.PositiveSmallIntegerField(null=True)),
                ('period', models.CharField(blank=True, max_length=2, null=True)),
                ('navi', models.CharField(blank=True, max_length=2, null=True)),
                ('info', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.CharField(blank=True, max_length=20, null=True)),
                ('mt_bevollm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mt_bevollm', to='asys.agent')),
                ('mt_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mt_receiver', to='asys.agent')),
                ('mt_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mt_sender', to='asys.agent')),
                ('sys_cp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sys_cp', to=settings.AUTH_USER_MODEL)),
                ('sys_mt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sys_mt', to='asys.agent')),
            ],
            options={
                'db_table': 'a_sys',
            },
        ),
        migrations.CreateModel(
            name='UtaInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_ta', models.CharField(blank=True, max_length=75, null=True)),
                ('sub_ta', models.CharField(blank=True, max_length=50, null=True)),
                ('version_ta', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'u_ta_int',
            },
        ),
        migrations.CreateModel(
            name='Atermin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thema_item', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_item', models.CharField(blank=True, max_length=40, null=True)),
                ('asys', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='asys.asys')),
            ],
            options={
                'db_table': 'a_termin',
            },
        ),
        migrations.CreateModel(
            name='Atalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thema_item', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_item', models.CharField(blank=True, max_length=40, null=True)),
                ('asys', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='asys.asys')),
            ],
            options={
                'db_table': 'a_talk',
            },
        ),
        migrations.AddField(
            model_name='asys',
            name='utaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='asys.utaint'),
        ),
        migrations.CreateModel(
            name='AqAnda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_q', models.TextField(blank=True, null=True)),
                ('item_a', models.TextField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('asys', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='asys.asys')),
            ],
            options={
                'db_table': 'a_qanda',
            },
        ),
        migrations.CreateModel(
            name='AiSysDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmsp', models.DateTimeField(auto_now=True)),
                ('day', models.PositiveSmallIntegerField(null=True)),
                ('month', models.PositiveSmallIntegerField(null=True)),
                ('year', models.PositiveSmallIntegerField(null=True)),
                ('period', models.CharField(blank=True, max_length=2, null=True)),
                ('datum_type', models.CharField(choices=[('liefer', 'liefer'), ('leistung', 'leistung'), ('termin', 'termin')], max_length=10, null=True)),
                ('zeitraum', models.CharField(choices=[('zeitraum', 'zeitraum'), ('x', 'x')], max_length=10, null=True)),
                ('d_beginn_tmsp', models.DateTimeField(null=True)),
                ('d_beginn_item_day', models.PositiveSmallIntegerField(null=True)),
                ('d_beginn_item_month', models.PositiveSmallIntegerField(null=True)),
                ('d_beginn_item_year', models.PositiveSmallIntegerField(null=True)),
                ('d_beginn_item_period', models.CharField(blank=True, max_length=2, null=True)),
                ('d_end_tmsp', models.DateTimeField(null=True)),
                ('d_end_item_day', models.PositiveSmallIntegerField(null=True)),
                ('d_end_item_month', models.PositiveSmallIntegerField(null=True)),
                ('d_end_item_year', models.PositiveSmallIntegerField(null=True)),
                ('d_end_item_period', models.CharField(blank=True, max_length=2, null=True)),
                ('d_beginn_minute', models.PositiveSmallIntegerField(null=True)),
                ('d_beginn_hour', models.PositiveSmallIntegerField(null=True)),
                ('d_end_minute', models.PositiveSmallIntegerField(null=True)),
                ('d_end_hour', models.PositiveSmallIntegerField(null=True)),
                ('asys', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asys.asys')),
            ],
            options={
                'db_table': 'ai_sys_date',
            },
        ),
    ]
