# Generated by Django 3.2.6 on 2022-03-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisysdate',
            name='day',
            field=models.PositiveSmallIntegerField(default=7, null=True),
        ),
        migrations.AlterField(
            model_name='aisysdate',
            name='month',
            field=models.PositiveSmallIntegerField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='aisysdate',
            name='year',
            field=models.PositiveSmallIntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='asys',
            name='day',
            field=models.PositiveSmallIntegerField(default=7, null=True),
        ),
        migrations.AlterField(
            model_name='asys',
            name='month',
            field=models.PositiveSmallIntegerField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='asys',
            name='year',
            field=models.PositiveSmallIntegerField(default=2022, null=True),
        ),
    ]
