# Generated by Django 3.2.6 on 2022-03-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asys', '0002_auto_20220307_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='atermin',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='atermin',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atermin',
            name='telefon',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='aisysdate',
            name='day',
            field=models.PositiveSmallIntegerField(default=11, null=True),
        ),
        migrations.AlterField(
            model_name='asys',
            name='day',
            field=models.PositiveSmallIntegerField(default=11, null=True),
        ),
    ]
