# Generated by Django 3.2.6 on 2022-06-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asys', '0003_auto_20220311_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisysdate',
            name='day',
            field=models.PositiveSmallIntegerField(default=6, null=True),
        ),
        migrations.AlterField(
            model_name='aisysdate',
            name='month',
            field=models.PositiveSmallIntegerField(default=6, null=True),
        ),
        migrations.AlterField(
            model_name='asys',
            name='day',
            field=models.PositiveSmallIntegerField(default=6, null=True),
        ),
        migrations.AlterField(
            model_name='asys',
            name='month',
            field=models.PositiveSmallIntegerField(default=6, null=True),
        ),
    ]
