# Generated by Django 4.0.5 on 2022-06-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asys', '0004_auto_20220606_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisysdate',
            name='day',
            field=models.PositiveSmallIntegerField(default=24, null=True),
        ),
        migrations.AlterField(
            model_name='asys',
            name='day',
            field=models.PositiveSmallIntegerField(default=24, null=True),
        ),
    ]
