# Generated by Django 4.0.5 on 2022-10-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asys', '0005_alter_aisysdate_day_alter_asys_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisysdate',
            name='day',
            field=models.PositiveSmallIntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='aisysdate',
            name='month',
            field=models.PositiveSmallIntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='asys',
            name='day',
            field=models.PositiveSmallIntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='asys',
            name='month',
            field=models.PositiveSmallIntegerField(default=10, null=True),
        ),
        migrations.CreateModel(
            name='Athema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thema_item', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_item', models.CharField(blank=True, max_length=40, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('asys', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='asys.asys')),
            ],
            options={
                'db_table': 'a_thema',
            },
        ),
        migrations.CreateModel(
            name='Akommentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('aisysdate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asys.aisysdate')),
                ('athema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='asys.athema')),
            ],
            options={
                'db_table': 'a_kommentar',
            },
        ),
    ]
