# Generated by Django 4.0.5 on 2022-10-06 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asys', '0006_alter_aisysdate_day_alter_aisysdate_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='akommentar',
            old_name='content',
            new_name='kommentar',
        ),
        migrations.RemoveField(
            model_name='akommentar',
            name='aisysdate',
        ),
        migrations.AddField(
            model_name='akommentar',
            name='asys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='asys.asys'),
        ),
        migrations.AlterField(
            model_name='aisysdate',
            name='day',
            field=models.PositiveSmallIntegerField(default=6, null=True),
        ),
        migrations.AlterField(
            model_name='asys',
            name='day',
            field=models.PositiveSmallIntegerField(default=6, null=True),
        ),
    ]
