# Generated by Django 3.2.6 on 2021-10-14 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('catnr', models.BigIntegerField(null=True)),
                ('cat0', models.CharField(blank=True, max_length=25, null=True)),
                ('cat1', models.CharField(blank=True, max_length=25, null=True)),
                ('cat2', models.CharField(blank=True, max_length=25, null=True)),
                ('cat3', models.CharField(blank=True, max_length=25, null=True)),
                ('lastchanged', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cat',
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'method',
            },
        ),
        migrations.CreateModel(
            name='Mt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('intnr', models.BigIntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'mt',
            },
        ),
        migrations.CreateModel(
            name='Nugget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('menge', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('einzelpreis', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('einheit', models.CharField(blank=True, max_length=10, null=True)),
                ('addonflag', models.BooleanField(default=False)),
                ('description_long', models.CharField(blank=True, max_length=200, null=True)),
                ('nuggetnr', models.BigIntegerField(null=True)),
                ('pic_url', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
                ('lastchanged', models.DateTimeField(auto_now=True)),
                ('mt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt')),
            ],
            options={
                'db_table': 'nugget',
            },
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('lastchanged', models.DateTimeField(auto_now=True)),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.method')),
                ('mt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt')),
            ],
            options={
                'db_table': 'paymentdetail',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('intnr', models.BigIntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Pp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('ext_datum', models.DateField(blank=True, null=True)),
                ('lastchanged', models.DateTimeField(auto_now=True)),
                ('mt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.status')),
            ],
            options={
                'db_table': 'pp',
            },
        ),
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('lastchanged', models.DateTimeField(auto_now=True)),
                ('mt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt')),
                ('paymentdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.paymentdetail')),
            ],
            options={
                'db_table': 'paypal',
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('pairnr', models.BigIntegerField(null=True)),
                ('namevorname', models.CharField(blank=True, max_length=100, null=True)),
                ('strassenr', models.CharField(blank=True, max_length=150, null=True)),
                ('plzstadt', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonnr', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('addzusatz', models.CharField(blank=True, max_length=50, null=True)),
                ('lastchanged', models.DateTimeField(auto_now=True)),
                ('mt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt')),
            ],
            options={
                'db_table': 'pair',
            },
        ),
        migrations.CreateModel(
            name='OptionCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('mt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt')),
            ],
            options={
                'db_table': 'option_cat',
            },
        ),
        migrations.CreateModel(
            name='NuggetCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('lastchanged', models.DateTimeField(auto_now=True)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.cat')),
                ('mt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt')),
                ('nugget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.nugget')),
            ],
            options={
                'db_table': 'nugget_cat',
            },
        ),
        migrations.AddField(
            model_name='nugget',
            name='optioncat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.optioncat'),
        ),
        migrations.AddField(
            model_name='mt',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.user'),
        ),
        migrations.CreateModel(
            name='Folg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('lastchanged', models.DateTimeField(auto_now=True)),
                ('counter', models.IntegerField(null=True)),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.method')),
                ('mt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt')),
                ('pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.pair')),
                ('paymentdetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.paymentdetail')),
                ('pp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.pp')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.status')),
            ],
            options={
                'db_table': 'folg',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('mt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt')),
            ],
            options={
                'db_table': 'domain',
            },
        ),
        migrations.AddField(
            model_name='cat',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('lastchanged', models.DateTimeField(auto_now=True)),
                ('mt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt')),
                ('paymentdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.paymentdetail')),
            ],
            options={
                'db_table': 'cash',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('menge', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('einzelpreis', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('einheit', models.CharField(blank=True, max_length=10, null=True)),
                ('group', models.IntegerField(null=True)),
                ('addonCount', models.IntegerField(null=True)),
                ('addonflag', models.BooleanField(default=False)),
                ('lastchanged', models.DateTimeField(auto_now=True)),
                ('folg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.folg')),
                ('mt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt')),
                ('nugget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.nugget')),
            ],
            options={
                'db_table': 'basket',
            },
        ),
    ]
