# Generated by Django 3.1.7 on 2021-03-26 05:28

from django.db import migrations

def create_data(apps, schema_editor):
    Product = apps.get_model('cashier', 'Products')
    Product(description='Product1').save()

class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
