# Generated by Django 3.1.7 on 2021-03-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
