# Generated by Django 3.2.6 on 2022-03-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_alter_basket_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
