# Generated by Django 3.2.6 on 2022-06-06 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_alter_basket_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='folg',
            name='paypaldetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.paypal'),
        ),
    ]
