# Generated by Django 3.1.7 on 2021-03-26 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_auto_20210326_0545'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
