# Generated by Django 3.1.7 on 2021-03-28 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashier', '0004_auto_20210326_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('catnr', models.BigIntegerField(null=True)),
                ('cat1', models.CharField(blank=True, max_length=25, null=True)),
                ('cat2', models.CharField(blank=True, max_length=25, null=True)),
                ('cat3', models.CharField(blank=True, max_length=25, null=True)),
                ('lastchanged', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cat',
            },
        ),
        migrations.CreateModel(
            name='Folg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('lastchanged', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'folg',
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'method',
            },
        ),
        migrations.CreateModel(
            name='Nugget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('nuggetnr', models.BigIntegerField(null=True)),
                ('lastchanged', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nugget',
            },
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('lastchanged', models.DateTimeField(auto_now=True)),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.method')),
            ],
            options={
                'db_table': 'paymentdetail',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('lastchanged', models.DateTimeField(auto_now=True)),
                ('folg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.folg')),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.method')),
                ('nugget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.nugget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shopping_cart',
            },
        ),
        migrations.CreateModel(
            name='Pp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('ext_datum', models.DateField(blank=True, null=True)),
                ('lastchanged', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.status')),
            ],
            options={
                'db_table': 'pp',
            },
        ),
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('lastchanged', models.DateTimeField(auto_now=True)),
                ('paymentdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.paymentdetail')),
            ],
            options={
                'db_table': 'paypal',
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('pairnr', models.BigIntegerField(null=True)),
                ('namevorname', models.CharField(blank=True, max_length=100, null=True)),
                ('strassenr', models.CharField(blank=True, max_length=150, null=True)),
                ('plzstadt', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonnr', models.CharField(blank=True, max_length=50, null=True)),
                ('lastchanged', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pair',
            },
        ),
        migrations.AddField(
            model_name='nugget',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.status'),
        ),
        migrations.AddField(
            model_name='folg',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.method'),
        ),
        migrations.AddField(
            model_name='folg',
            name='pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.pair'),
        ),
        migrations.AddField(
            model_name='folg',
            name='paymentdetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.paymentdetail'),
        ),
        migrations.AddField(
            model_name='folg',
            name='pp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.pp'),
        ),
        migrations.AddField(
            model_name='folg',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.status'),
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('lastchanged', models.DateTimeField(auto_now=True)),
                ('paymentdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.paymentdetail')),
            ],
            options={
                'db_table': 'cash',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('lastchanged', models.DateTimeField(auto_now=True)),
                ('folg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.folg')),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.method')),
                ('nugget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.nugget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'basket',
            },
        ),
    ]
