# Generated by Django 3.1.7 on 2021-04-14 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0005_auto_20210328_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nugget',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.cat'),
        ),
    ]
