# Generated by Django 3.1.7 on 2021-04-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0006_auto_20210414_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='cat0',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
