# Generated by Django 3.1.7 on 2021-04-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0007_cat_cat0'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='description_long',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
