# Generated by Django 3.1.7 on 2021-04-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0010_auto_20210415_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='nugget',
            name='pic_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nugget',
            name='description_long',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
