# Generated by Django 3.2 on 2021-05-12 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0011_auto_20210415_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'domain',
            },
        ),
        migrations.CreateModel(
            name='Mt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('intnr', models.BigIntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'mt',
            },
        ),
        migrations.CreateModel(
            name='OptionCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('mt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt')),
            ],
            options={
                'db_table': 'option_cat',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('intnr', models.BigIntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.RemoveField(
            model_name='basket',
            name='method',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='user',
        ),
        migrations.AddField(
            model_name='basket',
            name='addonCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='addonflag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basket',
            name='einheit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='einzelpreis',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='group',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='menge',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='folg',
            name='counter',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nugget',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nugget',
            name='addonflag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nugget',
            name='einheit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='nugget',
            name='einzelpreis',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='nugget',
            name='menge',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pair',
            name='addzusatz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pair',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
        migrations.AddField(
            model_name='mt',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.user'),
        ),
        migrations.AddField(
            model_name='domain',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
        migrations.AddField(
            model_name='basket',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
        migrations.AddField(
            model_name='cash',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
        migrations.AddField(
            model_name='cat',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
        migrations.AddField(
            model_name='folg',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
        migrations.AddField(
            model_name='nugget',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
        migrations.AddField(
            model_name='nugget',
            name='optioncat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.optioncat'),
        ),
        migrations.AddField(
            model_name='nuggetcat',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
        migrations.AddField(
            model_name='pair',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
        migrations.AddField(
            model_name='paypal',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
        migrations.AddField(
            model_name='pp',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
    ]
