# Generated by Django 3.1.7 on 2021-04-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0011_auto_20210415_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='method',
        ),
        migrations.AddField(
            model_name='basket',
            name='addonflag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basket',
            name='einheit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='einzelpreis',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='group',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='menge',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='nugget',
            name='addonflag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nugget',
            name='einheit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='nugget',
            name='einzelpreis',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='nugget',
            name='menge',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
