# Generated by Django 3.1.7 on 2021-04-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0012_auto_20210420_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='nugget',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
