# Generated by Django 3.1.7 on 2021-04-21 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0013_nugget_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('intnr', models.BigIntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Mt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('intnr', models.BigIntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.user')),
            ],
            options={
                'db_table': 'mt',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('mt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt')),
            ],
            options={
                'db_table': 'domain',
            },
        ),
        migrations.AddField(
            model_name='basket',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
        migrations.AddField(
            model_name='cash',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
        migrations.AddField(
            model_name='cat',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
        migrations.AddField(
            model_name='folg',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
        migrations.AddField(
            model_name='nugget',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
        migrations.AddField(
            model_name='nuggetcat',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
        migrations.AddField(
            model_name='pair',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
        migrations.AddField(
            model_name='paypal',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
        migrations.AddField(
            model_name='pp',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
    ]
