# Generated by Django 3.1.7 on 2021-04-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0014_auto_20210421_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'option_cat',
            },
        ),
    ]
