# Generated by Django 3.1.7 on 2021-04-22 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0016_nugget_optioncat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nugget',
            name='optioncat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.optioncat'),
        ),
    ]
