# Generated by Django 3.1.7 on 2021-04-22 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0017_auto_20210422_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='optioncat',
            name='mt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.mt'),
        ),
    ]
