# Generated by Django 3.1.7 on 2021-04-28 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0018_optioncat_mt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='user',
        ),
    ]
