# Generated by Django 3.1.7 on 2021-05-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0021_auto_20210429_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
